apiVersion: batch/v1
kind: Job
metadata:
  name: create-efs-dirs
spec:
  template:
    spec:
      containers:
      - name: efs-utils
        image: amazon/amazon-ecs-cli-v2:latest
        command: ["/bin/sh", "-c", "mkdir -p /mnt/efs/voice-app-uploads /mnt/efs/voice-app-output"]
        volumeMounts:
        - name: efs-volume
          mountPath: /mnt/efs
      restartPolicy: Never
      volumes:
      - name: efs-volume
        persistentVolumeClaim:
          claimName: voice-app-output # Update with your PVC name
