
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-data-voice-app-redis-master-0
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05a9f4e8cd5b29a71:/redis-master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-data-voice-app-redis-replicas-0
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05a9f4e8cd5b29a71:/redis-replicas
