apiVersion: batch/v1
kind: CronJob
metadata:
  name: voice-app-cleanup
  namespace: voice-app
spec:
  schedule: "0 * * * *"  # Run every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: busybox
            command:
            - /bin/sh
            - -c
            - |
              find /app/uploads -type f -mmin +60 -delete
              find /app/output -type f -mmin +60 -delete
              echo "Cleanup completed at $(date)"
            volumeMounts:
            - name: uploads
              mountPath: /app/uploads
            - name: output
              mountPath: /app/output
          restartPolicy: OnFailure
          volumes:
          - name: uploads
            persistentVolumeClaim:
              claimName: voice-app-uploads  # Make sure this matches your uploads PVC name
          - name: output
            persistentVolumeClaim:
              claimName: voice-app-output   # Make sure this matches your output PVC name
