@startuml
!define RECTANGLE
!define CLOUD

skinparam linetype ortho

cloud "Route 53" as route53
rectangle "Internet Gateway" as igw

rectangle "VPC" {
    rectangle "Public Subnets" {
        rectangle "NAT Gateway" as nat
        rectangle "NGINX Ingress" as nginx
    }
    
    rectangle "Private Subnets" {
        rectangle "EKS Cluster" as eks {
            rectangle "Node Group" {
                rectangle "EC2 Instances" as ec2
            }
        }
        rectangle "EFS" as efs
    }
}

rectangle "ACM" as acm
rectangle "IAM" as iam
rectangle "External DNS" as externaldns

route53 -down-> igw
igw -down-> VPC

VPC -down-> nat
VPC -down-> nginx
VPC -down-> eks
VPC -down-> efs

acm -up-> VPC
iam -up-> VPC
externaldns -up-> VPC

@enduml